version: '3.7'
services:
        envoy: 
                image: envoyproxy/envoy-alpine:v1.10.0
                volumes:
                        - ./envoy.yaml:/etc/envoy/envoy.yaml
                ports:
                - 127.0.0.1:7777:7777
                - 127.0.0.1:9901:9901
